import { Pool } from 'pg';
import dotenv from 'dotenv';
dotenv.config();

const pool = new Pool({
  connectionString: 'postgresql://postgres.hkbkvnaptnhkoghuredj:b263AGY5JTSRPFrh@aws-0-eu-west-1.pooler.supabase.com:6543/postgres',
  ssl: { rejectUnauthorized: false }
});

(async () => {
    try {
        await pool.query(`
            CREATE TABLE IF NOT EXISTS reviews (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                "userId" BIGINT REFERENCES users(id) ON DELETE CASCADE,
                "courseId" BIGINT REFERENCES courses(id) ON DELETE CASCADE,
                "eventId" BIGINT REFERENCES events(id) ON DELETE CASCADE,
                rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
                comment TEXT,
                "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
            );
        `);
        console.log("Table 'reviews' created successfully.");
    } catch (e: any) {
        console.error("error:", e.message);
    } finally {
        pool.end();
    }
})();
