-- Create Tables for Clinisphere IF NOT EXISTS

-- 1. Instructors
CREATE TABLE IF NOT EXISTS instructors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    specialty TEXT NOT NULL,
    bio TEXT,
    image TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 2. Users
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    role TEXT DEFAULT 'user',
    specialty TEXT,
    city TEXT,
    phone TEXT,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 3. Courses
CREATE TABLE IF NOT EXISTS courses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    "shortDescription" TEXT NOT NULL,
    "fullDescription" TEXT NOT NULL,
    price DECIMAL NOT NULL,
    "discountPrice" DECIMAL,
    currency TEXT DEFAULT 'DH',
    thumbnail TEXT NOT NULL,
    "previewVideo" TEXT,
    category TEXT NOT NULL,
    level TEXT DEFAULT 'beginner',
    "instructorId" BIGINT REFERENCES instructors(id) ON DELETE SET NULL,
    duration TEXT,
    "totalLessons" INTEGER DEFAULT 0,
    language TEXT DEFAULT 'Français',
    tags JSONB DEFAULT '[]'::jsonb,
    "isFeatured" BOOLEAN DEFAULT FALSE,
    "isPublished" BOOLEAN DEFAULT TRUE,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 4. Modules
CREATE TABLE IF NOT EXISTS modules (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "courseId" BIGINT REFERENCES courses(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    "order" INTEGER NOT NULL
);

-- 5. Lessons
CREATE TABLE IF NOT EXISTS lessons (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "moduleId" BIGINT REFERENCES modules(id) ON DELETE CASCADE,
    title TEXT NOT NULL,
    description TEXT,
    "videoUrl" TEXT,
    content TEXT,
    duration TEXT,
    "isFreePreview" BOOLEAN DEFAULT FALSE,
    "order" INTEGER NOT NULL
);

-- 6. Settings
CREATE TABLE IF NOT EXISTS settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL
);

-- 7. Home Slider
CREATE TABLE IF NOT EXISTS home_slider (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type TEXT NOT NULL,
    url TEXT NOT NULL,
    title TEXT,
    subtitle TEXT,
    "buttonText" TEXT,
    "buttonLink" TEXT,
    "order" INTEGER DEFAULT 0,
    "isActive" BOOLEAN DEFAULT TRUE
);

-- 8. Orders
CREATE TABLE IF NOT EXISTS orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "userId" BIGINT REFERENCES users(id),
    "totalPrice" DECIMAL NOT NULL,
    status TEXT DEFAULT 'pending',
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 9. Order Items
CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "orderId" BIGINT REFERENCES orders(id) ON DELETE CASCADE,
    "courseId" BIGINT REFERENCES courses(id),
    price DECIMAL NOT NULL
);

-- 10. Contacts
CREATE TABLE IF NOT EXISTS contacts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email TEXT NOT NULL,
    message TEXT NOT NULL,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 11. Events
CREATE TABLE IF NOT EXISTS events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title_en TEXT NOT NULL,
    title_fr TEXT NOT NULL,
    description_en TEXT NOT NULL,
    description_fr TEXT NOT NULL,
    "eventDate" TIMESTAMP WITH TIME ZONE NOT NULL,
    location TEXT NOT NULL,
    type TEXT NOT NULL, -- 'free' or 'paid'
    price DECIMAL DEFAULT 0,
    banner TEXT NOT NULL,
    status TEXT DEFAULT 'published', -- 'draft' or 'published'
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- 12. Articles
CREATE TABLE IF NOT EXISTS articles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title TEXT NOT NULL,
    slug TEXT UNIQUE NOT NULL,
    excerpt TEXT,
    content TEXT NOT NULL,
    image TEXT,
    author TEXT,
    category TEXT,
    "isPublished" BOOLEAN DEFAULT TRUE,
    "createdAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- --- RLS POLICIES ---
-- Enable RLS on all tables
ALTER TABLE instructors ENABLE ROW LEVEL SECURITY;
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE courses ENABLE ROW LEVEL SECURITY;
ALTER TABLE modules ENABLE ROW LEVEL SECURITY;
ALTER TABLE lessons ENABLE ROW LEVEL SECURITY;
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE home_slider ENABLE ROW LEVEL SECURITY;
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE order_items ENABLE ROW LEVEL SECURITY;
ALTER TABLE contacts ENABLE ROW LEVEL SECURITY;
ALTER TABLE events ENABLE ROW LEVEL SECURITY;
ALTER TABLE articles ENABLE ROW LEVEL SECURITY;

-- Policy creation with safety checks
DO $$ 
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on published events') THEN
        CREATE POLICY "Allow public read on published events" ON events FOR SELECT USING (status = 'published');
    END IF;
    
    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on events') THEN
        CREATE POLICY "Allow admins all on events" ON events FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on published articles') THEN
        CREATE POLICY "Allow public read on published articles" ON articles FOR SELECT USING ("isPublished" = TRUE);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on articles') THEN
        CREATE POLICY "Allow admins all on articles" ON articles FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on instructors') THEN
        CREATE POLICY "Allow public read on instructors" ON instructors FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on instructors') THEN
        CREATE POLICY "Allow admins all on instructors" ON instructors FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on users') THEN
        CREATE POLICY "Allow public read on users" ON users FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow individual users to update own profile') THEN
        CREATE POLICY "Allow individual users to update own profile" ON users FOR UPDATE USING (auth.uid()::text = email) WITH CHECK (auth.uid()::text = email);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on users') THEN
        CREATE POLICY "Allow admins all on users" ON users FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on courses') THEN
        CREATE POLICY "Allow public read on courses" ON courses FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on courses') THEN
        CREATE POLICY "Allow admins all on courses" ON courses FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on modules') THEN
        CREATE POLICY "Allow public read on modules" ON modules FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on modules') THEN
        CREATE POLICY "Allow admins all on modules" ON modules FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on lessons') THEN
        CREATE POLICY "Allow public read on lessons" ON lessons FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on lessons') THEN
        CREATE POLICY "Allow admins all on lessons" ON lessons FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on settings') THEN
        CREATE POLICY "Allow public read on settings" ON settings FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on settings') THEN
        CREATE POLICY "Allow admins all on settings" ON settings FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow public read on home_slider') THEN
        CREATE POLICY "Allow public read on home_slider" ON home_slider FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on home_slider') THEN
        CREATE POLICY "Allow admins all on home_slider" ON home_slider FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow users to read own orders') THEN
        CREATE POLICY "Allow users to read own orders" ON orders FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow users to create orders') THEN
        CREATE POLICY "Allow users to create orders" ON orders FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins all on orders') THEN
        CREATE POLICY "Allow admins all on orders" ON orders FOR ALL USING (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow everyone to create contacts') THEN
        CREATE POLICY "Allow everyone to create contacts" ON contacts FOR INSERT WITH CHECK (true);
    END IF;

    IF NOT EXISTS (SELECT 1 FROM pg_policies WHERE policyname = 'Allow admins to read contacts') THEN
        CREATE POLICY "Allow admins to read contacts" ON contacts FOR SELECT USING (true);
    END IF;
END $$;

-- --- DEFAULT DATA ---

-- Insert Instructors
INSERT INTO instructors (name, specialty, bio, image) VALUES 
('Dr. Sarah Amrani', 'Gynécologie-Obstétrique', 'Experte en échographie fœtale avec plus de 15 ans d''expérience clinique.', 'https://images.unsplash.com/photo-1559839734-2b71f153678e?auto=format&fit=crop&q=80&w=400&h=400'),
('Pr. Karim Benali', 'Cardiologie Pédiatrique', 'Chef de service émérite spécialisé dans les malformations cardiaques pédiatriques.', 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?auto=format&fit=crop&q=80&w=400&h=400'),
('Dr. Yasmine Tazi', 'Néonatologie', 'Spécialiste en soins intensifs néonataux et réanimation pédiatrique.', 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?auto=format&fit=crop&q=80&w=400&h=400')
ON CONFLICT DO NOTHING;

-- Insert Settings
INSERT INTO settings (key, value) VALUES 
('currencyCode', 'MAD'),
('currencySymbol', 'DH'),
('currencyPosition', 'right'),
('headerLogo', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_font_awesome.svg'),
('footerLogo', 'https://upload.wikimedia.org/wikipedia/commons/d/d3/User_font_awesome.svg'),
('logoLink', '/'),
('sliderButton1Text', 'JOIN NOW'),
('sliderButton1Link', '/register'),
('sliderButton1Enabled', '1'),
('sliderButton2Text', 'CATALOGUE'),
('sliderButton2Link', '/courses'),
('sliderButton2Enabled', '1')
ON CONFLICT (key) DO NOTHING;

-- Insert Sample Courses
INSERT INTO courses (title, slug, "shortDescription", "fullDescription", price, "discountPrice", thumbnail, category, level, "instructorId", duration, "totalLessons", "isFeatured", "isPublished") VALUES 
('Échographie Obstétricale de Base', 'echographie-obstetricale-base', 'Apprenez les bases de l''échographie obstétricale avec des experts.', 'Ce cours complet couvre les principes fondamentaux de l''échographie en obstétrique, de la manipulation de la sonde à l''interprétation des images du premier trimestre.', 1500, 1200, 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&q=80&w=800', 'Gynécologie', 'beginner', 1, '10h', 12, true, true),
('Cardiologie Pédiatrique Avancée', 'cardiologie-pediatrique-avancee', 'Diagnostic et prise en charge des cardiopathies congénitales.', 'Formation approfondie sur les pathologies cardiaques chez l''enfant et le nouveau-né.', 2500, 2000, 'https://images.unsplash.com/photo-1628177142898-93e36e4e3a50?auto=format&fit=crop&q=80&w=800', 'Cardiologie', 'advanced', 2, '15h', 20, true, true)
ON CONFLICT (slug) DO NOTHING;

-- Insert Sample Modules
INSERT INTO modules (id, "courseId", title, "order") 
VALUES (1, 1, 'Introduction à l''Échographie', 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO modules (id, "courseId", title, "order") 
VALUES (2, 1, 'Le Premier Trimestre', 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO modules (id, "courseId", title, "order") 
VALUES (3, 2, 'Fondamentaux du Cœur Pédiatrique', 0) ON CONFLICT (id) DO NOTHING;

-- Insert Sample Lessons
INSERT INTO lessons (id, "moduleId", title, duration, "isFreePreview", "order") 
VALUES (1, 1, 'Principes Physiques des Ultrasons', '45 min', true, 0) ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, "moduleId", title, duration, "isFreePreview", "order") 
VALUES (2, 1, 'Réglages de l''Appareil', '30 min', false, 1) ON CONFLICT (id) DO NOTHING;
INSERT INTO lessons (id, "moduleId", title, duration, "isFreePreview", "order") 
VALUES (3, 2, 'Datation de la Grossesse', '1h', false, 0) ON CONFLICT (id) DO NOTHING;
